name: Publish
on:
    release:
        types: [published]

permissions:
    contents: write
    id-token: write # Required for OIDC authentication.

jobs:
    test_and_sync:
        uses: apify/fingerprint-suite/.github/workflows/test-and-sync.yml@master
        secrets: inherit

    publish_latest:
        name: Publish latest
        runs-on: ubuntu-22.04
        needs: [test_and_sync]
        steps:
            - name: Checkout Source code
              uses: actions/checkout@v6
              with:
                  token: ${{ secrets.APIFY_SERVICE_ACCOUNT_GITHUB_TOKEN }}

            - name: Use Node.js
              uses: actions/setup-node@v6
              with:
                  node-version: 24
                  cache: 'npm'
                  registry-url: 'https://registry.npmjs.org/'
                  cache-dependency-path: 'package-lock.json'

            - name: Turbo cache
              id: turbo-cache
              uses: actions/cache@v5
              with:
                  path: .turbo
                  key: turbo-${{ github.job }}-${{ github.ref_name }}-${{ github.sha }}
                  restore-keys: |
                      turbo-${{ github.job }}-${{ github.ref_name }}-

            - name: Install Dependencies
              run: npm ci

            - name: Release latest versions
              run: |
                  git config --global user.name 'Apify Release Bot'
                  git config --global user.email 'noreply@apify.com'

                  export GIT_TAG=$(echo $GITHUB_REF | sed 's/refs\/tags\///g')
                  npm run release

            - name: Commit the version bump
              uses: stefanzweifel/git-auto-commit-action@v7
              with:
                  branch: master
                  commit_message: 'chore: [skip ci] sync new package.json versions'
                  file_pattern: 'package*.json'
                  commit_user_name: Apify Bot
                  commit_user_email: my-github-actions-bot@example.org
                  commit_author: Apify Bot <apify@apify.com>

    publish_to_pypi:
        name: Publish to PyPI
        needs: [publish_latest]
        runs-on: ubuntu-latest
        steps:
            - name: Execute publish workflow
              uses: apify/workflows/execute-workflow@main
              with:
                  workflow: release_python.yaml
