name: Publish
on:
    release:
        types: [published]

jobs:
    test_and_sync:
        uses: apify/fingerprint-suite/.github/workflows/test-and-sync.yml@master
        secrets: inherit

    publish_latest:
        name: Publish latest
        runs-on: ubuntu-22.04
        needs: [test_and_sync]
        steps:
            - name: Checkout Source code
              uses: actions/checkout@v5
              with:
                  token: ${{ secrets.APIFY_SERVICE_ACCOUNT_GITHUB_TOKEN }}

            - name: Use Node.js 22
              uses: actions/setup-node@v4
              with:
                  node-version: 22
                  cache: 'npm'
                  cache-dependency-path: 'package-lock.json'

            - name: Turbo cache
              id: turbo-cache
              uses: actions/cache@v4
              with:
                  path: .turbo
                  key: turbo-${{ github.job }}-${{ github.ref_name }}-${{ github.sha }}
                  restore-keys: |
                      turbo-${{ github.job }}-${{ github.ref_name }}-

            - name: Install Dependencies
              run: npm ci

            - name: Release latest versions
              run: |
                  git config --global user.name 'Apify Release Bot'
                  git config --global user.email 'noreply@apify.com'

                  echo "access=public" >> ~/.npmrc
                  echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" >> ~/.npmrc

                  export GIT_TAG=$(echo $GITHUB_REF | sed 's/refs\/tags\///g')
                  npm run release
              env:
                  NPM_TOKEN: ${{ secrets.APIFY_SERVICE_ACCOUNT_NPM_TOKEN }}
                  GIT_USER: 'noreply@apify.com:${{ secrets.APIFY_SERVICE_ACCOUNT_GITHUB_TOKEN }}'
                  GH_TOKEN: ${{ secrets.APIFY_SERVICE_ACCOUNT_GITHUB_TOKEN }}

            - name: Commit the version bump
              uses: stefanzweifel/git-auto-commit-action@v6
              with:
                  branch: master
                  commit_message: 'chore: [skip ci] sync new package.json versions'
                  file_pattern: 'package*.json'
                  commit_user_name: Apify Bot
                  commit_user_email: my-github-actions-bot@example.org
                  commit_author: Apify Bot <apify@apify.com>
