name: Run tests

on:
    # Push to master will deploy a dev version
    push:
        branches: [ main, renovate/** ]
    # PR to master branch will skip deployment
    pull_request:
        branches: [ main ]
    # A release via GitHub releases will deploy the latest version
    release:
        types: [ published ]
    workflow_dispatch:

jobs:
    build_and_test:
        name: Build & Test
        if: ${{ !contains(github.event.head_commit.message, '[skip ci]') }}
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                os: [ ubuntu-latest ]
                node-version: [ 15, 16 ]

        steps:
            -
                uses: actions/checkout@v2
            -
                name: Use Node.js ${{ matrix.node-version }}
                uses: actions/setup-node@v1
                with:
                    node-version: ${{ matrix.node-version }}
            -
                name: Install playwright deps
                run : npx playwright install-deps
            -
                name: Install Dependencies
                run: npm ci
            -
                name: Cache Node Modules
                if: ${{ matrix.node-version == 16 }}
                uses: actions/cache@v2
                with:
                    path: |
                        node_modules
                    key: cache-${{ github.run_id }}-v16
            -
                name: Run Windows or MacOs tests
                run: npm test
                if: ${{ matrix.os == 'windows-latest' || matrix.os == 'macos-latest' }}
            -
                name: Run Linux tests
                run: xvfb-run --auto-servernum -- npm test
                if: ${{ matrix.os == 'ubuntu-latest'}}

    lint:
        name: Lint
        needs: [build_and_test]
        runs-on: ubuntu-latest

        steps:
            -
                uses: actions/checkout@v2
            -
                name: Use Node.js 16
                uses: actions/setup-node@v1
                with:
                    node-version: 16
            -
                name: Load Cache
                uses: actions/cache@v2
                with:
                    path: |
                        node_modules
                    key: cache-${{ github.run_id }}-v16
            -
                run: npm run lint

    # publish:
    #     name: Publish
    #     if: (github.ref == 'refs/heads/master' || github.event_name == 'release') && !contains(github.event.head_commit.message, '[skip ci]')
    #     runs-on: ubuntu-latest
    #     needs: [ lint, build_and_test ]
    #     steps:
    #         -   name: Checkout Source code
    #             uses: actions/checkout@v3

    #         -   name: Use Node.js 16
    #             uses: actions/setup-node@v3
    #             with:
    #                 node-version: 16
    #                 cache: 'npm'
    #                 cache-dependency-path: 'package-lock.json'

    #         -   name: Turbo cache
    #             id: turbo-cache
    #             uses: actions/cache@v2
    #             with:
    #                 path: .turbo
    #                 key: turbo-${{ github.job }}-${{ github.ref_name }}-${{ github.sha }}
    #                 restore-keys: |
    #                     turbo-${{ github.job }}-${{ github.ref_name }}-

    #         -   name: Install Dependencies
    #             run: npm ci

    #         -   name: Check for changes
    #             id: changed_packages
    #             run: |
    #                 echo "::set-output name=changed_packages::$(node ./node_modules/.bin/lerna changed -p | wc -l | xargs)"

    #         -   name: Check for changes 2
    #             if: steps.changed_packages.outputs.changed_packages == '0'
    #             run: |
    #                 echo "no changes detected by lerna"

    #         -   name: Build
    #             if: steps.changed_packages.outputs.changed_packages != '0'
    #             run: npm run build

    #         -   name: Set Release Tag
    #             run: echo "RELEASE_TAG=$(if [ ${{ github.event_name }} = release ]; then echo latest; else echo next; fi)" >> $GITHUB_ENV

    #         -   name: Release dev version for testing
    #             if: env.RELEASE_TAG == 'next' && steps.changed_packages.outputs.changed_packages != '0'
    #             run: |
    #                 git config --global user.name 'Apify Release Bot'
    #                 git config --global user.email 'noreply@apify.com'
    #                 npx turbo run copy --force -- -- --canary
    #                 git commit -am 'chore: bump canary versions [skip ci]'

    #                 echo "access=public" >> .npmrc
    #                 echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" >> .npmrc
    #                 npm run publish:next -- --yes --no-verify-access
    #             env:
    #                 NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    #                 GIT_USER: "noreply@apify.com:${{ secrets.GH_TOKEN }}"
    #                 GH_TOKEN: ${{ secrets.GH_TOKEN }}

# TODO this will need adjustments, as the root package.json is no longer usable
# The deploy job is long but there are only 2 important parts. NPM publish
# and triggering of docker image builds in the apify-actor-docker repo.
#            -   name: Collect Versions For Images
#                id: versions
#                run: |
#                    apify=`node -p "require('./package.json').version"`
#                    echo "::set-output name=apify::$apify"
#                    puppeteer=`node -p "require('./package.json').devDependencies.puppeteer"`
#                    echo "::set-output name=puppeteer::$puppeteer"
#                    playwright=`node -p "require('./package.json').devDependencies.playwright"`
#                    echo "::set-output name=playwright::$playwright"
#                env:
#                    NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
#                    GIT_USER: "noreply@apify.com:${{ secrets.GH_TOKEN }}"
#                    GH_TOKEN: ${{ secrets.GH_TOKEN }}
#            -   name: Trigger Docker Image Build
#                uses: peter-evans/repository-dispatch@v2
#                with:
#                    token: ${{ secrets.TRIGGER_DOCKER_IMAGE_BUILD_TOKEN }}
#                    repository: apify/apify-actor-docker
#                    event-type: build-node-images
#                    client-payload: >
#                        {
#                          "release_tag": "${{ env.RELEASE_TAG }}",
#                          "apify_version": "${{ steps.versions.outputs.apify }}",
#                          "puppeteer_version": "${{ steps.versions.outputs.puppeteer }}",
#                          "playwright_version": "${{ steps.versions.outputs.playwright }}"
#                        }
