name: Run tests

on:
    # Push to master will deploy a dev version, push to stable deploys the latest version (and syncs the master branch)
    push:
        branches: [master, stable]
    # PRs will run tests (skip deployment)
    pull_request:
        branches: [master, stable]
    # A release via GitHub releases will deploy the latest version
    workflow_call:
    workflow_dispatch:

env:
    APIFY_HTTPBIN_TOKEN: ${{ secrets.APIFY_HTTPBIN_TOKEN }}

jobs:
    lint:
        name: Lint
        if: ${{ !contains(github.event.head_commit.message, '[skip ci]') }}
        runs-on: ubuntu-22.04

        steps:
            - uses: actions/checkout@v5
            - name: Use Node.js 22
              uses: actions/setup-node@v4
              with:
                  node-version: 22

            - name: Install Dependencies
              run: npm ci

            - name: Load Cache
              uses: actions/cache@v4
              with:
                  path: |
                      node_modules
                  key: cache-${{ github.run_id }}

            - run: npm run lint

    build_and_test:
        name: Build & Test
        needs: [lint]
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                os: [ubuntu-22.04]
                node-version: [20, 22, 24]

        steps:
            - uses: actions/checkout@v5
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Cache Node Modules
              uses: actions/cache@v4
              with:
                  path: |
                      node_modules
                  key: cache-${{ github.run_id }}

            - name: Install Playwright deps
              run: npx playwright install --with-deps

            - name: Install Puppeteer deps
              run: |
                  npx puppeteer browsers install chrome
                  npx puppeteer browsers install firefox

            - name: Turbo cache
              id: turbo-cache
              uses: actions/cache@v4
              with:
                  path: .turbo
                  key: turbo-${{ github.job }}-${{ github.ref_name }}-${{ github.sha }}
                  restore-keys: |
                      turbo-${{ github.job }}-${{ github.ref_name }}-

            - name: Build
              run: npm run build

            - name: Run Windows or MacOs tests
              run: npm test
              if: ${{ matrix.os == 'windows-latest' || matrix.os == 'macos-latest' }}

            - name: Run Linux tests
              run: xvfb-run --auto-servernum -- npm test
              if: ${{ matrix.os == 'ubuntu-22.04'}}
